"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "python"
style = "plain"
template = "({{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }})"
foreground = "white"

[blocks.segments.properties]
fetch_version = false

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
template = "╭─"
foreground = "#81ff91"

[[blocks.segments]]
type = 'os'
style = 'diamond'
foreground = '#81ff91'
# background = "#282a36"
template = ' {{.Icon}}{{ if .WSL }}WSL at {{ end }} '

[blocks.segments.properties]
alpine = ""
arch = ""
centos = ""
debian = ""
elementary = ""
fedora = ""
gentoo = ""
linux = ""
macos = ""
manjaro = ""
mint = ""
opensuse = ""
raspbian = ""
ubuntu = ""
windows = ""
wsl = ""

[[blocks.segments]]
type = "session"
style = "plain"
template = "<#f9b5ac> {{ .UserName }}</> <d><#73a7a7>w</></d> "

[[blocks.segments]]
type = "path"
style = "plain"
template = " {{ .Path }} "
foreground = "#b87ea2"

[blocks.segments.properties]
style = "full"

[[blocks.segments]]
type = "git"
style = "diamond"
template = "<#db6e89>::</> {{ .UpstreamIcon }}{{ .HEAD }}{{ if .Staging.Changed }}<#FF6F00>  {{ .Staging.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
foreground = "#c9cccd"

[blocks.segments.properties]
fetch_status = true
fetch_stash_count = true
fetch_upstream_icon = true

[[blocks]]
alignment = "right"
type = "prompt"

[[blocks.segments]]
type = "time"
style = "plain"
template = "[{{ .CurrentDate | date .Format }}] "
foreground = "#81ff91"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
template = "╰─"
foreground = "#81ff91"

[[blocks]]
type = "prompt"
alignment = "left"
newline = false

[[blocks.segments]]
type = "text"
style = "plain"
template = "❯"
foreground = "#81ff91"
