"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
console_title_template = "{{if .Root}}[root] {{end}}{{.Shell}}: <{{.Folder}}>"
version = 3
final_space = true

[palette]
bg_green = "#A7C080"
fg_green = "#425047"
aqua = "#83C092"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

# os
[[blocks.segments]]
type = "os"
style = "plain"
foreground = "p:bg_green"
template = "{{ if .WSL }}WSL at {{ end }}{{.Icon}}"

# Host
[[blocks.segments]]
foreground = "p:bg_green"
template = " {{ if .SSHSession }} {{ end }}{{ .UserName }}@{{ .HostName }} "
style = "diamond"
type = "session"

[blocks.segments.properties]
display_host = true

# Path
[[blocks.segments]]
foreground = "p:bg_green"
template = "{{ .Path }}"
style = "powerline"
type = "path"

[blocks.segments.properties]
cache_duration = 'none'
home_icon = '~'
max_depth = 5
folder_separator_icon = " "
style = "agnoster_full"
right_format = '<p:aqua>%s</>'

[[blocks]]
alignment = "right"
type = "prompt"

[[blocks.segments]]
template = " {{ .Name }}"
foreground = "p:bg_green"
type = "shell"
style = "diamond"

[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
foreground = "p:bg_green"
style = "plain"
type = "text"

[[blocks.segments]]
style = "diamond"
template = "  "
type = "root"

[blocks.segments.properties]
root_icon = " "

[[blocks.segments]]
type = "time"
style = "diamond"
foreground = "p:bg_green"
template = " {{.CurrentDate | date .Format }}"

[blocks.segments.properties]
cache_duration = 'none'
time_format = ' 02.01.2006  15:04:05'

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

[[blocks.segments]]
foreground = "#A9FFB4"
foreground_templates = ["{{ if gt .Code 0 }}#ef5350{{ end }}"]
style = "plain"
template = " "
type = "status"

[blocks.segments.properties]
always_enabled = true

[transient_prompt]
background = "transparent"
foreground = "#FEF5ED"
template = " "


[[blocks]]
alignment = "right"
type = "rprompt"

[[blocks.segments]]
template = "{{ if gt .Code 0 }} {{ else }} {{ end }}"
foreground = "#A7C080"
type = "status"
style = "diamond"
foreground_templates = ["{{ if gt .Code 0 }}#425047 {{ end }}"]

[blocks.segments.properties]
always_enabled = true
cache_duration = "none"

[[blocks.segments]]
foreground = "#A7C080"
style = "diamond"
template = "{{ .FormattedMs }}s"
type = "executiontime"

[blocks.segments.properties]
style = "dallas"
threshold = 0

[[blocks.segments]]
template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}[{{ .Venv }}] <#A8D5BA>🐍</> {{ .Full }}{{ end }}{{ end }}'
foreground = "p:bg_green"
type = 'python'
style = 'powerline'

[blocks.segments.properties]
fetch_virtual_env = true
folder_name_fallback = false
fetch_version = true
cache_duration = 'none'

# git
[[blocks.segments]]
foreground = "p:bg_green"
template = " {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
type = "git"
style = "diamond"
foreground_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#D08770{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#EBCB8B{{ end }}",
    "{{ if gt .Ahead 0 }}#B48EAD{{ end }}",
    "{{ if gt .Behind 0 }}#B48EAD{{ end }}",
]

[blocks.segments.properties]
cache_duration = "none"
fetch_stash_count = true
fetch_status = true
fetch_upstream_icon = true
