version = 2
final_space = true

[[blocks]]
    type = "prompt"
    alignment = "left"

[[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "p:ein-03"
    template = "╭─<#ffd966>[</>{{ if .SSHSession }}  {{ end }}"

[[blocks.segments]]
    type = "os"
    style = "plain"
    foreground = "p:ein-01"
    template = "{{ .UserName }}@{{ .HostName }}<#ffd966>]</> <#ffd966>{{.Icon}}</>"

[[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "p:ein-02"

[blocks.segments.properties]
    folder_icon = " "
    folder_separator_icon = " 󰅂 "
    home_icon = ""
    max_depth = 4
    style = "agnoster_short"


[[blocks]]
    type = "prompt"
    alignment = "right"

[[blocks.segments]]
    type = "status"
    style = "plain"
    foreground = "p:ein-03"
    foreground_templates = ["{{ if gt .Code 0 }}red{{ end }}"]
    template = " {{ if gt .Code 0 }}✘ {{ else }}󰸞 {{ end }}{{ if eq ( gt .Code 0 ) .Segments.Path.Writable}} {{ end }}"

[blocks.segments.properties]
    always_enabled = true

[[blocks.segments]]
    type = "executiontime"
    style = "powerline"
    foreground = "p:ein-01"
    template = " <#fefefe></> {{ .FormattedMs }} "

[properties]
    threshold = 500
    style = "austin"
    always_enabled = true

[[blocks.segments]]
    type = "git"
    style = "plain"
    foreground = "p:ein-01"
    template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} 󰆓 {{ .StashCount }}{{ end }}"

[blocks.segments.properties]
    branch_icon = " "
    fetch_stash_count = true
    fetch_status = true
    fetch_worktree_count = true

[[blocks.segments]]
    type = "python"
    style = "powerline"
    foreground = "p:ein-01"
    fetch_virtual_env = true
    fetch_version = true
    template = " <#ffd966> </> {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"

[[blocks.segments]]
    type = "time"
    style = "plain"
    foreground = "p:ein-01"
    template = " {{ .CurrentDate | date .Format }} "

[blocks.segments.properties]
    time_format = " <#ffd966> </> 15:04:05 <#ffd966> </> 2006-01-02"

[[blocks]]
    type = "prompt"
    alignment = "left"
    newline = true

[[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "p:ein-01"
    template = "<p:ein-03>╰─󰅂</>"

[palette]
    ein-01 = "#7e7e7e"
    ein-02 = "#e5e5e5"
    ein-03 = "#ffd966"
